version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 6.20.12
    - 6.20.14
    - 6.20.17
    - 6.20.18
    - 6.20.19
    - 6.20.20
    - 6.20.22
    - 6.20.23
    - 6.20.24
    - 6.20.25
  - dependency-name: doctrine/dbal
    versions:
    - 2.12.1
    - 2.13.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: nunomaduro/collision
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: laravel/tinker
    versions:
    - 2.6.0
  - dependency-name: barryvdh/laravel-dompdf
    versions:
    - 0.9.0
  - dependency-name: fzaninotto/faker
    versions:
    - 1.9.2
  - dependency-name: barryvdh/laravel-ide-helper
    versions:
    - 2.8.2
  - dependency-name: fideloper/proxy
    versions:
    - 4.4.1
